### ISSUE TITLE
MAS not working properly with Probe Control Room

### ISSUE THREAD

**Issue by kurgut** [MOARdV/AvionicsSystems#372] opened 2023-12-04 08:42 UTC
So I edited the Mission Control internal to add MAS props, but once in KSP, they do not respond to inputs (clicking on buttons/switches/MFD), they do produce a sound on click tho. However if you change scene or switch between vessels, you'll see that your input got applied, the screen have changed page, and the switches gone into the good position.
I tested all the cockpits I have which use MAS, and no issue like that.
Should mention that a user said this happened to him when trying to edit DECK's Apollo/LEM IVA, but no more info.

Of course, the part on my vessel has a MASflihtcomputer module.

Here's the log, doesn't complain too much that's the point, so I couldn't figure out what was wrong :
https://www.dropbox.com/scl/fi/5wlxecidqcxtu2y3khq2f/KSP.zip?rlkey=03c8smk90blqeir3t6vkvsdbx&dl=0

I'll reference this issue in PCR git too.

Thank you : )

**Comment by JonnyOThan** [comment] 2024-02-29 13:53
dupe of #331

**Closed by JonnyOThan** 2024-02-29 13:53 UTC
Labels: duplicate
